[package]
name = "petscan_rs"
version = "0.1.0"
authors = ["Magnus Manske <magnusmanske@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1"
#chrono = "0.4.6"
config = "0.9.2"
serde_json = "1.0.39"
#urlencoding = "1.0.0"
#roxmltree = "0.6.0"
#rocket = "0.4.2"
hyper = "0.12.31"
#mediawiki = "0.1.7"
mediawiki =  { git = "https://github.com/magnusmanske/mediawiki_rust" }
#wikibase = "0.3"
#wikibase = { git = "https://gitlab.com/tobias47n9e/wikibase_rs" }
wikibase = { path='../wikibase_rs' }
