[package]
name = "petscan_rs"
version = "0.1.0"
authors = ["Magnus Manske <magnusmanske@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1"
chrono = "0.4.6"
config = "0.9.2"
#serde = "1.0.94"
serde_json = "1.0.39"
url = "1.7.2"
rayon = "1.1.0"
rocket = "0.4.2"
rocket_contrib = "0.4.2"
rand = "0.7.0"
mysql = { version="16.0.2" , features = ["ssl"] }

#mediawiki = "0.1.7"
mediawiki =  { git = "https://github.com/magnusmanske/mediawiki_rust" }
#wikibase = "0.3"
wikibase = { git = "https://gitlab.com/tobias47n9e/wikibase_rs" }
#wikibase = { path='../wikibase_rs' }
