[package]
name = "petscan_rs"
version = "0.1.0"
authors = ["Magnus Manske <magnusmanske@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1"
chrono = "*"
config = "*"
serde_json = "*"
url = "*"
rayon = "*"
htmlescape = "*"
rand = "*"
mysql = { version="16.0.2" , features = ["ssl"] }
reqwest = "*"
rocket = "*"
rocket_contrib = "*"
#rocket =  { git = "https://github.com/SergioBenitez/Rocket" }
#rocket_contrib =  { git = "https://github.com/SergioBenitez/Rocket" }

#mediawiki = "0.1.7"
#mediawiki =  { git = "https://github.com/magnusmanske/mediawiki_rust" }
#mediawiki = { path='../mediawiki' }

#wikibase = "0.3"
wikibase = { git = "https://gitlab.com/tobias47n9e/wikibase_rs" }
#wikibase = { path='../wikibase_rs' }

